espn_ffb/views/awards.py
from flask import Blueprint, render_template

awards = Blueprint("awards", __name__, template_folder="templates")


@awards.route('/awards/<int:year>', methods=['GET'])
def show(year: int):
    return render_template(f"awards/{year}.html", title=f'{year} Awards')

espn_ffb/views/champions.py
from collections import namedtuple
from flask import Blueprint, current_app, render_template

champions = Blueprint("champions", __name__, template_folder="templates")
TABLE_HEADERS = ['Year', 'Champion']
COLUMN_NAMES = ['year', 'champion']
Record = namedtuple('Champions', COLUMN_NAMES)


def get_records(query):
    records = list()
    champions, owners = zip(*query.get_champions())

    for c, o in zip(champions, owners):
        records.append(Record(year=c.year, champion=o.first_name + " " + o.last_name))

    return records


@champions.route('/champions', methods=['GET'])
def show():
    query = current_app.config.get("QUERY")
    records = get_records(query)

    return render_template('champions.html', title='Champions', table_headers=TABLE_HEADERS,
                           column_names=COLUMN_NAMES, records=records)

espn_ffb/views/h2h_records.py
from flask import Blueprint, current_app, render_template, request
from espn_ffb import util

h2h_records = Blueprint("h2h_records", __name__, template_folder="templates")
TABLE_HEADERS = ['Opponent', 'Wins', 'Losses']
COLUMN_NAMES = ['opponent_name', 'wins', 'losses']


@h2h_records.route('/h2h-records', methods=['GET'])
def show():
    query = current_app.config.get("QUERY")

    matchup_type = request.args.get('matchup_type', default=util.REGULAR_SEASON)
    owner_id = request.args.get('owner_id', type=str)

    owners = query.get_owners(exclude=True)
    is_playoffs = util.get_is_playoffs(matchup_type)

    if not owner_id:
        owner_id = owners[0].id

    records = query.get_h2h_records(owner_id=owner_id, is_playoffs=is_playoffs)
    return render_template("h2h-records.html", title='H2H Records', table_headers=TABLE_HEADERS,
                           column_names=COLUMN_NAMES, matchup_type=matchup_type, owners=owners, selected_owner=owner_id,
                           records=records)

espn_ffb/views/home.py
from flask import Blueprint, render_template

home = Blueprint("home", __name__, template_folder="templates")


@home.route('/home', methods=['GET'])
def show():
    return render_template("home.html", title='Home')

espn_ffb/views/matchup_history.py
from flask import Blueprint, current_app, render_template, request
from espn_ffb import util

matchup_history = Blueprint("matchup_history", __name__, template_folder="templates")
TABLE_HEADERS = ["Year", "Matchup ID", "Team", "Opponent Score", "Result"]
COLUMN_NAMES = ["year", "matchup_id", "team_score", "opponent_team_score", "is_win"]


@matchup_history.route('/matchup-history', methods=['GET'])
def show():
    query = current_app.config.get("QUERY")

    matchup_type = request.args.get('matchup_type', default=util.REGULAR_SEASON)
    owner_id = request.args.get('owner_id', type=str)
    opponent_owner_id = request.args.get('opponent_owner_id', type=str)

    owners = query.get_owners(exclude=True)
    is_playoffs = util.get_is_playoffs(matchup_type)

    if not owner_id:
        owner_id = owners[0].id
        opponent_owner_id = owners[1].id

    records = query.get_matchup_history(owner_id=owner_id, opponent_owner_id=opponent_owner_id, is_playoffs=is_playoffs)
    return render_template('matchup-history.html', title='Matchup History', table_headers=TABLE_HEADERS,
                           column_names=COLUMN_NAMES, matchup_type=matchup_type, owners=owners, selected_owner=owner_id,
                           selected_opponent=opponent_owner_id, records=records)

espn_ffb/views/playoffs.py
from flask import Blueprint, render_template

playoffs = Blueprint("playoffs", __name__, template_folder="templates")


@playoffs.route('/playoffs/<int:year>', methods=['GET'])
def show(year):
    # noinspection PyUnresolvedReferences
    return render_template(f"playoffs/{year}.html", title='{year} Playoffs')

espn_ffb/views/recap.py
from flask import Blueprint, current_app, render_template
from espn_ffb import util

recap = Blueprint("recap", __name__, template_folder="templates")


@recap.route('/recap/<int:year>/<int(fixed_digits=2):week>', methods=['GET'])
def show(year, week):
    query = current_app.config.get("QUERY")

    team_ids = set(query.get_distinct_matchup_team_ids(year)[week])
    matchups = [m for m in query.get_matchups(year) if m.matchup_id == week and m.team_id in team_ids]
    matchups = sorted(matchups, key=lambda m: m.team_id)
    win_streaks = query.get_win_streak_by_year(matchups, year, week)
    team_id_to_record = query.get_team_id_to_record(year, week)
    team_id_to_team_name = query.get_team_id_to_team_name(year)
    h2h_records = query.get_h2h_record_current(matchups, year, week)

    recaps = list()
    for m, ws, h2h_record in zip(matchups, win_streaks, h2h_records):
        streak_owner = team_id_to_team_name.get(ws.streak_owner)

        recaps.append(
            util.Recap(
                team=team_id_to_team_name[m.team_id],
                team_record=team_id_to_record[m.team_id],
                opponent=team_id_to_team_name[m.opponent_team_id],
                opponent_record=team_id_to_record[m.opponent_team_id],
                streak=ws.streak,
                streak_owner=streak_owner,
                h2h_record=h2h_record,
                body=f"recap/{year}/{week:02d}/{m.team_id}.html"
            )
        )
    return render_template("recap.html", title='Weekly Recap', recaps=recaps)

espn_ffb/views/standings.py
from flask import Blueprint, current_app, render_template, request
from espn_ffb import util

standings = Blueprint("standings", __name__, template_folder="templates")
TABLE_HEADERS = ["Name", "Wins", "Losses", "Ties", "Win Percentage", "Points For", "Points Against", "Average Points For",
                 "Average Points Against", "Championships", "Sackos"]
COLUMN_NAMES = ["owner_id", "wins", "losses", "ties", "win_percentage", "points_for", "points_against", "avg_points_for",
                "avg_points_against", "championships", "sackos"]


def get_owner_id_to_name(query):
    return {o.id: o.first_name + " " + o.last_name for o in query.get_owners()}


@standings.route('/standings/<string:year>', methods=['GET'])
def show(year: str):
    # return "<h1 style='color:blue'>Hello There!</h1>" + str(sys.argv[1])
    query = current_app.config.get("QUERY")

    matchup_type = request.args.get('matchup_type', default=util.REGULAR_SEASON)
    owner_id_to_name = get_owner_id_to_name(query)
    sacko = query.get_sacko_current()
    is_playoffs = util.get_is_playoffs(matchup_type=matchup_type)

    if year == "overall":
        records = query.get_standings(is_playoffs=is_playoffs)
    else:
        records = query.get_standings(year=int(year), is_playoffs=is_playoffs)

    return render_template('standings.html', title='Standings', table_headers=TABLE_HEADERS, column_names=COLUMN_NAMES,
                           records=records, sacko=sacko, owner_id_to_name=owner_id_to_name, matchup_type=matchup_type,
                           year=year)

espn_ffb/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.22/b-1.6.4/b-colvis-1.6.4/b-html5-1.6.4/b-print-1.6.4/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/recap.css') }}"/>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-static-top">
      <a class="navbar-brand mr-auto" href="#">Art Hung Appreciation League&nbsp;</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myTopnav" aria-controls="myTopnav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="myTopnav">
        <ul class="nav navbar-nav nav-pills">
          <!-- {%- if awards_templates_years %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle {% block nav_awards %}{% endblock %}" href="#" id="navbarAwards" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Awards
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarAwards">
                {%- for year in awards_templates_years %}
                  <a class="dropdown-item" href="{{ url_for('awards.show', year=year) }}">{{ year }}</a>
                {%- endfor %}
              </div>
            </li>
          {%- endif %} -->
         <li class="nav-item">
            <a class="nav-link {% block nav_home %}{% endblock %}" href="{{ url_for('home.show') }}" >Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% block nav_standings %}{% endblock %}" href="#" id="navbarStandings" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Standings
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarStandings">
              <a class="dropdown-item" href="{{ url_for('standings.show', year='overall') }}">Overall</a>
              <div class="dropdown-divider"></div>
              {%- for year in years %}
                <a class="dropdown-item" href="{{ url_for('standings.show', year=year) }}">{{ year }}</a>
              {%- endfor %}
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block nav_h2h %}{% endblock %}" href="{{ url_for('h2h_records.show') }}">H2H Records</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block nav_matchups %}{% endblock %}" href="{{ url_for('matchup_history.show') }}" >Matchup History</a>
          </li>
          {%- if recap_templates_year_weeks %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle {% block nav_recap %}{% endblock %}" href="#" id="navbarRecap" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Recap
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarRecap">
                {%- for year_month in recap_templates_year_weeks %}
                  <a class="dropdown-item" href="{{ url_for('recap.show', year=year_month[0], week=year_month[1]) }}">{{ year_month[0] }}, Week {{ '%02d' % year_month[1] }}</a>
                {%- endfor %}
              </div>
            </li>
          {%- endif %}
          <li class="nav-item">
            <a class="nav-link {% block nav_champions %}{% endblock %}" href="{{ url_for('champions.show') }}">Champions</a>
          </li>
          {%- if playoffs_templates_years %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle {% block nav_playoffs %}{% endblock %}" href="#" id="navbarPlayoffs" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Playoffs
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarPlayoffs">
                {%- for year in playoffs_templates_years %}
                  <a class="dropdown-item" href="{{ url_for('playoffs.show', year=year) }}">{{ year }}</a>
                {%- endfor %}
              </div>
            </li>
          {%- endif %}
        </ul>
      </div>
    </nav>
    {%- block content %}{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!-- DataTables -->
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.22/b-1.6.4/b-colvis-1.6.4/b-html5-1.6.4/b-print-1.6.4/datatables.min.js"></script>
    <script src="{{ url_for('static', filename='js/sort.js') }}"></script>

  </body>
</html>

espn_ffb/templates/champions.html
{%- extends "base.html" -%}
{% block nav_champions %}active{% endblock %}
{%- block content -%}
  {%- if records|length > 0 %}
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            {%- for th in table_headers %}
            <th>{{ th }}</th>
            {%- endfor %}
          </tr>
        </thead>
        <tbody>
          {%- for r in records %}
            <tr>{%- for cn in column_names %}<td>{{ r[cn] }}</td>{%- endfor %}</tr>
          {%- endfor %}
        </tbody>
      </table>
    </div>
  {%- endif %}
{%- endblock -%}

espn_ffb/templates/h2h-records.html
{%- extends "base.html" -%}
{% block nav_h2h %}active{% endblock %}
{%- block content %}
<div> <br> 
  Change Seen Here
  </div>
  <form class="form-inline" action="{{ url_for('h2h_records.show') }}" method="get">
    <select class="custom-select m-2" name="owner_id" onchange="this.form.submit()">
    {%- for o in owners %}
      <option value="{{ o.id }}" {%- if o.id == selected_owner %} selected {% endif %}>{{o.first_name + " " + o.last_name }}</option>
    {%- endfor %}
    </select>
    <div class="form-check form-check-inline m-2">
      <input class="form-check-input" id="regularSeasonSelect" type="radio" name="matchup_type" value="regular" onclick="this.form.submit()" {%- if matchup_type == "regular" %} checked {% endif %}></input>
      <label class="form-check-label" for="regularSeasonSelect">Regular Season</label>
    </div>
    <div class="form-check form-check-inline m-2">
      <input class="form-check-input" id="playoffSelect" type="radio" name="matchup_type" value="playoffs" onclick="this.form.submit()"{%- if matchup_type == "playoffs" %} checked {% endif %}></input>
      <label class="form-check-label" for="playoffSelect">Playoffs</label>
    </div>
  </form>
  {%- if records|length > 0 %}
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          {%- for th in table_headers %}
          <th>{{ th }}</th>
          {%- endfor %}
        </tr>
      </thead>
      <tbody>
        {%- for r in records %}
        <tr>
          {%- for cn in column_names %}
          <td>{{ r[cn] }}</td>
          {%- endfor %}
        </tr>
        {%- endfor %}
      </tbody>
    </table>
  </div>
  {%- endif %}
{%- endblock -%}

espn_ffb/templates/matchup-history.html
{%- extends "base.html" -%}
{% block nav_matchups %}active{% endblock %}
{%- block content -%}
  <form class="form-inline" action="{{ url_for('matchup_history.show') }}" method="get">
    <label class="m-2" for="owner_id">Owner:</label>
    <select class="custom-select m-2" name="owner_id" onchange="this.form.submit()">
    {%- for o in owners %}
      <option value="{{ o.id }}" {%- if o.id == selected_owner %} selected {% endif %}>{{o.first_name + " " + o.last_name }}</option>
    {%- endfor %}
    </select>
    <label class="m-2" for="opponent_owner_id">Opponent:</label>
    <select class="custom-select m-2" name="opponent_owner_id" onchange="this.form.submit()">
    {%- for o in owners %}
      {%- if o.owner_id != selected_owner %}
      <option value="{{ o.id }}" {%- if o.id == selected_opponent %} selected {% endif %}>{{ o.first_name + " " + o.last_name }}</option>
        {%- endif -%}
      {%- endfor %}
    </select>
    <div class="form-check form-check-inline m-2">
      <input class="form-check-input" id="regularSeasonSelect" type="radio" name="matchup_type" value="regular" onclick="this.form.submit()" {%- if matchup_type == "regular" %} checked {% endif %}></input>
      <label class="form-check-label" for="regularSeasonSelect">Regular Season</label>
    </div>
    <div class="form-check form-check-inline m-2">
      <input class="form-check-input" id="playoffSelect" type="radio" name="matchup_type" value="playoffs" onclick="this.form.submit()"{%- if matchup_type == "playoffs" %} checked {% endif %}></input>
      <label class="form-check-label" for="playoffSelect">Playoffs</label>
    </div>
  </form>
  {%- if records|length > 0 %}
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          {%- for th in table_headers %}
          <th>{{ th }}</th>
          {%- endfor %}
        </tr>
      </thead>
      <tbody>
        {%- for r in records %}
        <tr>
          {%- for cn in column_names %}
          {%- if cn == "is_win" %}
            {%- if r[cn] %}
          <td>W</td>
            {%- else %}
           <td>L</td>
            {%- endif %}
          {%- else %}
          <td>{{ r[cn] }}</td>
          {%- endif %}
          {%- endfor %}
        </tr>
        {%- endfor %}
      </tbody>
    </table>
  </div>
  {%- endif %}
{%- endblock -%}

espn_ffb/templates/recap.html
{%- extends "base.html" %}
{% block recap_css %}<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/recap.css') }}"/>{% endblock %}
{% block nav_recap %}active{% endblock %}
{%- block content %}
  <div>
    <div class="column">
      {%- for r in recaps %}
      <div class="card">
        <h2>
          {{ r.team }} ({{ r.team_record.wins }}-{{ r.team_record.losses }})
          <br>
          vs.
          <br>
          {{ r.opponent }} ({{ r.opponent_record.wins }}-{{ r.opponent_record.losses }})
        </h2>
        <h5>All-time: ({{ r.h2h_record.wins }}-{{ r.h2h_record.losses }}), Win streak: {{ r.streak }} ({{ r.streak_owner }})</h5>
        <br>
        {%- include r.body %}
      </div>
      {%- endfor %}
    </div>
  </div>
{%- endblock %}

espn_ffb/templates/standings.html
{%- extends "base.html" -%}
{% block nav_standings %}active{% endblock %}
{%- block content -%}
  <form class="form-inline m-2" action="{{ url_for('standings.show', year=year) }}" method="get">
    <div class="form-check form-check-inline">
      <input class="form-check-input" id="regularSeasonSelect" type="radio" name="matchup_type" value="regular" onclick="this.form.submit()" {%- if matchup_type == "regular" %} checked {% endif %}></input>
      <label class="form-check-label" for="regularSeasonSelect">Regular Season</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" id="playoffSelect" type="radio" name="matchup_type" value="playoffs" onclick="this.form.submit()"{%- if matchup_type == "playoffs" %} checked {% endif %}></input>
      <label class="form-check-label" for="playoffSelect">Playoffs</label>
    </div>
  </form>
  {%- if records|length > 0 %}

{%- if year != 'overall' %}
  <div> <h3> View league page for the <a href="https://fantasy.espn.com/football/league/standings?seasonId={{year}}&leagueId=384382">{{year}} season </a> </h3> </div>
  {%- else %}
  <div> <br> 
  Change Seen Here
  </div>
  {%- endif %}

  <div class="table-responsive">
    <table id="standings" class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Rank</th>
          {%- for th in table_headers %}
          <th>{{ th }}</th>
          {%- endfor %}
        </tr>
      </thead>
      <tbody>
        {%- set count = namespace(a=1) %}
        {%- for r in records %}
        <tr>
          <td>{{ count.a }}</td>
          {%- for cn in column_names %}
          {%- if cn == "owner_id" %}
          <td>{{ owner_id_to_name.get(r[cn]) }}</td>
          {%- elif cn == "win_percentage" %}
          <td>{{ r[cn] | percentage_format }}</td>
          {%- elif cn == "points_for" or cn == "points_against" %}
          <td>{{ r[cn] | points_format }}</td>
          {%- elif cn == "championships" %}
          <td>
            {%- for c in range(0, r[cn]) %}
            <img height=60 src="{{ url_for('static', filename='images/trophy.png') }}"/>
            {%- endfor %}
          </td>
          {%- elif cn == "sackos" %}
          <td>
            {%- for d in range(0, r[cn]) -%}
            {%- if r['owner_id'] == sacko['owner_id'] %}
            <img height=60 src="{{ url_for('static', filename='images/sacko-current.png') }}"/>
            {%- else %}
            <img height=60 src="{{ url_for('static', filename='images/sacko.png') }}"/>
            {%- endif %}
            {%- endfor %}
          </td>
          {%- else %}
          <td>{{ r[cn] }}</td>
          {%- endif %}
          {%- endfor %}
        </tr>
        {%- set count.a = count.a + 1 %}
        {%- endfor %}
      </tbody>
    </table>
  </div>
  {%- endif %}
{%- endblock -%}